Books/Controllers/Get_BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Books.Controllers
{
    public class Get_BooksController : Controller
    {
        // GET: Get_Books
        public ActionResult Get_Books()
        {
            Repository.Repository Get_Books = new Repository.Repository();
            var Model = Get_Books.Get_Books();
            return View(Model);
        }
        
        public ActionResult Delete(Models.Book book)
        {
            Repository.Repository Get_Books = new Repository.Repository();
            Get_Books.Book_Removal(book);
            return RedirectPermanent("~/Get_Books/Get_Books");
        }

        public ActionResult Edit_Book(Models.Book book)  //форма редактирования записи
        {
            return View(book);            
        }

        public ActionResult New_Book(Models.Book book)    // запись измененной книги
        {
            Repository.Repository Get_Books = new Repository.Repository();
            Get_Books.Edit_Book(book);
            return RedirectPermanent("~/Get_Books/Get_Books");
        }
    }
}

Books/Views/Get_Books/Edit_Book.cshtml
@model Books.Models.Book

@using (Html.BeginForm(Html.BeginForm("New_Book", "Get_Books", FormMethod.Post)))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enter new Book details</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })  
        @Html.HiddenFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })                
        
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Language, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Language, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Language, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Books/Views/Get_Books/Get_Books.cshtml
@model IEnumerable<Books.Models.Book>

<h1>List Books</h1>
<table class="table">
    <tr>
        <th>
            @Html.Hidden("book.Id")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Language)
        </th>
        <th></th>
    </tr>

@foreach (var book in Model)
{
    <tr>      
        <td>
            @Html.Hidden((book.Id).ToString())         
        </td>    
         <td>
            @Html.DisplayFor(modelItem => book.Title)            
        </td>
        <td>
            @Html.DisplayFor(modelItem => book.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => book.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => book.Language)
        </td>
        <td> 
            @Html.ActionLink("Edit", "Edit_Book", new { book.Id})       
            @Html.ActionLink("Delete", "Delete", new { book.Id })
        </td>
    </tr>

}
</table>